version: "3"

services:
  app:
    build: ./
    ports: 
      - "80:80"
    links:
      - mysql
    volumes:
      - .:/usr/src/app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    volumes:
      - my-volume:/var/lib/mysql
volumes:
  my-volume:
    